// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-cib7kbDbJfUo_md_I8gMBp0UWXqRvhY',
    appId: '1:653683288960:web:9090704593e94ab1642f65',
    messagingSenderId: '653683288960',
    projectId: 'hbgapp-c3c88',
    authDomain: 'hbgapp-c3c88.firebaseapp.com',
    storageBucket: 'hbgapp-c3c88.firebasestorage.app',
    measurementId: 'G-BKLTMS7DQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfw_DT5q4wFGMa6MxL3YkyLQ3WxIB5byo',
    appId: '1:653683288960:android:4548693545b60066642f65',
    messagingSenderId: '653683288960',
    projectId: 'hbgapp-c3c88',
    storageBucket: 'hbgapp-c3c88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWtuiYsQrW6H7OFKSR53jVVjP1w7Um73A',
    appId: '1:653683288960:ios:7d173ae68860bdba642f65',
    messagingSenderId: '653683288960',
    projectId: 'hbgapp-c3c88',
    storageBucket: 'hbgapp-c3c88.firebasestorage.app',
    iosClientId: '653683288960-3d2pe922u8gqje6oqq0n2jugkci0ru87.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitbegoneAdmin',
  );
}
